version: 2.1

references:
  container_config: &container_config
    docker:
      - image: circleci/python:3.6.2
    working_directory: ~/repo

  workspace_root: &workspace_root /tmp/workspace
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  restore_repo: &restore_repo
    restore_cache:
      keys:
        - v1-repo-{{ .Branch }}-{{ .Revision }}
        - v1-repo-{{ .Branch }}
        - v1-repo

  requirements_cache_key: &requirements_cache_key v1-dependency-requirements-{{ checksum "requirements.txt" }}
  requirements_backup_cache_key: &requirements_backup_cache_key v1-dependency-requirements

  restore_python_packages: &restore_python_packages
    restore_cache:
      keys:
        - *requirements_cache_key
        - *requirements_backup_cache_key

jobs:
  checkout_code:
    <<: *container_config
    steps:
      - *restore_repo
      - checkout
      - save_cache:
          key: v1-repo-{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/repo

  install_dependencies:
    <<: *container_config
    steps:
      - *restore_repo
      - *restore_python_packages
      - run: sudo pip install virtualenv
      - run: virtualenv venv
      - run: source venv/bin/activate && pip install -r requirements.txt
      - save_cache:
          key: *requirements_cache_key
          paths:
            - ~/repo/venv/lib/python3.6/site-packages

  lint:
    <<: *container_config
    steps:
      - *restore_repo
      - *restore_python_packages
      - run: flake8

  test:
    <<: *container_config
    steps:
      - *restore_repo
      - *restore_python_packages
      - run: ./manage.py test

  stage:
    <<: *container_config
    steps:
      - *attach_workspace
      - run:
          name: Restore build assets from workspace
          command: |
            rm -rf build
            mv /tmp/workspace/build build
      - run: echo "Placeholder for deploy to staging"

  deploy:
    <<: *container_config
    steps:
      - *attach_workspace
      - run:
          name: Restore build assets from workspace
          command: |
            rm -rf build
            mv /tmp/workspace/build build
      - run: echo "Placeholder for deploy to prod"

workflows:
  version: 2
  lint_test_build_stage_deploy:
    jobs:
      - checkout_code
      - install_dependencies:
          requires:
            - checkout_code
      - lint:
          requires:
            - install_dependencies
      - test:
          requires:
            - install_dependencies
      - stage:
          requires:
            - lint
            - test
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - lint
            - test
          filters:
            branches:
              only: prod
              