# Generated by Django 2.2.1 on 2019-06-20 18:17

from django.db import migrations, models
import django.db.models.deletion
import report.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[(report.models.TrackerStatus('Active'), 'Active'), (report.models.TrackerStatus('Disabled'), 'Disabled'), (report.models.TrackerStatus('Retired'), 'Retired'), (report.models.TrackerStatus('Unresponsive'), 'Unresponsive'), (report.models.TrackerStatus('Unused'), 'Unused')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='date time recorded')),
                ('geo_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('geo_long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Tracker')),
            ],
        ),
    ]
