# Generated by Django 2.2.1 on 2019-06-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='geo_method',
            field=models.CharField(choices=[('G', 'GPS'), ('L', 'LTE'), ('B', 'GPS+LTE')], default=('L', 'LTE'), max_length=3),
        ),
    ]
