# Generated by Django 2.2.1 on 2019-07-08 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20190627_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='geo_accuracy',
            new_name='geo_error_radius',
        ),
        migrations.RenameField(
            model_name='tracker',
            old_name='desired_accuracy',
            new_name='max_error_radius',
        ),
    ]
