# Generated by Django 2.2.2 on 2019-07-22 21:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('animal_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('D', 'Disabled'), ('R', 'Retired'), ('U', 'Unresponsive'), ('X', 'Unused')], max_length=3)),
                ('max_error_radius', models.DecimalField(decimal_places=1, max_digits=5)),
                ('location_method', models.CharField(choices=[('G', 'GPS'), ('L', 'LTE'), ('B', 'GPS+LTE')], default=('B', 'GPS+LTE'), max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(verbose_name='date time recorded')),
                ('geo_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('geo_long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('geo_error_radius', models.DecimalField(decimal_places=1, max_digits=5)),
                ('geo_method', models.CharField(choices=[('G', 'GPS'), ('L', 'LTE'), ('B', 'GPS+LTE')], default=('L', 'LTE'), max_length=3)),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal.Tracker')),
            ],
        ),
    ]
