# Generated by Django 2.2.2 on 2019-07-23 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='geo_method',
            field=models.CharField(choices=[('G', 'GPS'), ('L', 'LTE'), ('B', 'GPS+LTE')], default='L', max_length=3),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='location_method',
            field=models.CharField(choices=[('G', 'GPS'), ('L', 'LTE'), ('B', 'GPS+LTE')], default='B', max_length=3),
        ),
    ]
