# Generated by Django 2.2.1 on 2019-07-11 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0004_auto_20190708_2152'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Record',
            new_name='Point',
        ),
    ]
